# Generated by Django 4.1.3 on 2023-03-23 13:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('homeAddress', models.CharField(max_length=200)),
                ('emailAddress', models.EmailField(max_length=254, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='')),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
